# CUDA_VISIBLE_DEVICES=0 python eval.py \
#     rlbench.tasks=\[a_stack_blocks\] \
#     rlbench.task_name='clip_place_blocks_take_1_p3' \
#     rlbench.demo_path=$PERACT_ROOT/data/val \
#     framework.gpu=0 \
#     framework.logdir=$PERACT_ROOT/logs/ \
#     framework.start_seed=0 \
#     framework.eval_envs=1 \
#     framework.eval_from_eps_number=0 \
#     framework.eval_episodes=10 \
#     framework.csv_logging=True \
#     framework.tensorboard_logging=True \
#     framework.eval_type='missing' \
#     rlbench.headless=True \
#     rlbench.episode_length=10

# CUDA_VISIBLE_DEVICES=0 python eval.py \
#     rlbench.tasks=\[a_stack_blocks\] \
#     rlbench.task_name='clip_place_blocks_take_2_p3' \
#     rlbench.demo_path=$PERACT_ROOT/data/val \
#     framework.gpu=0 \
#     framework.logdir=$PERACT_ROOT/logs/ \
#     framework.start_seed=0 \
#     framework.eval_envs=1 \
#     framework.eval_from_eps_number=0 \
#     framework.eval_episodes=10 \
#     framework.csv_logging=True \
#     framework.tensorboard_logging=True \
#     framework.eval_type='missing' \
#     rlbench.headless=True \
#     rlbench.episode_length=10

CUDA_VISIBLE_DEVICES=0 python eval.py \
    rlbench.tasks=\[a_blocks\] \
    rlbench.task_name='place_blocks_take_0_p3' \
    rlbench.demo_path=$PERACT_ROOT/data/val \
    framework.gpu=0 \
    framework.logdir=$PERACT_ROOT/logs/ \
    framework.start_seed=0 \
    framework.eval_envs=1 \
    framework.eval_from_eps_number=0 \
    framework.eval_episodes=10 \
    framework.csv_logging=True \
    framework.tensorboard_logging=True \
    framework.eval_type='best' \
    rlbench.headless=True \
    rlbench.episode_length=10

CUDA_VISIBLE_DEVICES=0 python eval.py \
    rlbench.tasks=\[a_blocks\] \
    rlbench.task_name='clip_place_blocks_take_1_p3' \
    rlbench.demo_path=$PERACT_ROOT/data/val \
    framework.gpu=0 \
    framework.logdir=$PERACT_ROOT/logs/ \
    framework.start_seed=0 \
    framework.eval_envs=1 \
    framework.eval_from_eps_number=0 \
    framework.eval_episodes=10 \
    framework.csv_logging=True \
    framework.tensorboard_logging=True \
    framework.eval_type='best' \
    rlbench.headless=True \
    rlbench.episode_length=10

CUDA_VISIBLE_DEVICES=0 python eval.py \
    rlbench.tasks=\[a_blocks\] \
    rlbench.task_name='clip_place_blocks_take_2_p3' \
    rlbench.demo_path=$PERACT_ROOT/data/val \
    framework.gpu=0 \
    framework.logdir=$PERACT_ROOT/logs/ \
    framework.start_seed=0 \
    framework.eval_envs=1 \
    framework.eval_from_eps_number=0 \
    framework.eval_episodes=10 \
    framework.csv_logging=True \
    framework.tensorboard_logging=True \
    framework.eval_type='best' \
    rlbench.headless=True \
    rlbench.episode_length=10
