CUDA_VISIBLE_DEVICES=0 python train.py \
    method=PERACT_BC \
    rlbench.tasks=\[insert_onto_square_peg\] \
    rlbench.task_name='clip_insert_peg_p3' \
    rlbench.cameras=\[front,left_shoulder,right_shoulder,wrist\] \
    rlbench.demos=100 \
    rlbench.demo_path=$PERACT_ROOT/data/peract_baseline/train \
    replay.batch_size=2 \
    replay.path=/tmp/replay \
    replay.max_parallel_processes=2 \
    method.voxel_sizes=\[100\] \
    method.voxel_patch_size=5 \
    method.voxel_patch_stride=5 \
    method.num_latents=2048 \
    method.transform_augmentation.apply_se3=True \
    method.transform_augmentation.aug_rpy=\[0.0,0.0,0.0\] \
    method.pos_encoding_with_lang=True \
    framework.training_iterations=20100\
    framework.num_weights_to_keep=15 \
    framework.start_seed=0 \
    framework.log_freq=500 \
    framework.save_freq=1000 \
    framework.logdir=$PERACT_ROOT/logs/100_demos/ \
    framework.csv_logging=True \
    framework.tensorboard_logging=True \
    ddp.num_devices=1 \
    rlbench.episode_length=10 \
    method.dense_clip_sims=True \
    method.no_rgb=True

CUDA_VISIBLE_DEVICES=0 python train.py \
    method=PERACT_BC \
    rlbench.tasks=\[close_jar\] \
    rlbench.task_name='test' \
    rlbench.cameras=\[front,left_shoulder,right_shoulder,wrist\] \
    rlbench.demos=2\
    rlbench.demo_path=$PERACT_ROOT/data/peract_baseline/train \
    replay.batch_size=4 \
    replay.path=$PERACT_ROOT/replay \
    replay.max_parallel_processes=10 \
    method.voxel_sizes=\[100\] \
    method.voxel_patch_size=5 \
    method.voxel_patch_stride=5 \
    method.num_latents=2048 \
    method.transform_augmentation.apply_se3=True \
    method.transform_augmentation.aug_rpy=\[0.0,0.0,45.0\] \
    method.pos_encoding_with_lang=True \
    framework.training_iterations=100\
    framework.num_weights_to_keep=10 \
    framework.start_seed=0 \
    framework.log_freq=10 \
    framework.save_freq=10 \
    framework.logdir=$PERACT_ROOT/logs/100_demos/ \
    framework.csv_logging=True \
    framework.tensorboard_logging=True \
    ddp.num_devices=1 \
    rlbench.episode_length=10 \
    method.dense_clip_sims=True \
    method.no_rgb=True

CUDA_VISIBLE_DEVICES=0 python eval.py \
    rlbench.tasks=[close_jar,light_bulb_in] \
    rlbench.task_name='clip_multi_jar_bulb_rls2' \
    rlbench.demo_path=$PERACT_ROOT/data/peract_baseline/val \
    framework.gpu=0 \
    framework.logdir=$PERACT_ROOT/logs/100_demos \
    framework.start_seed=0 \
    framework.eval_envs=4 \
    framework.eval_from_eps_number=0 \
    framework.eval_episodes=25 \
    framework.csv_logging=True \
    framework.tensorboard_logging=False \
    framework.eval_type='missing' \
    rlbench.headless=True \
    rlbench.episode_length=12

CUDA_VISIBLE_DEVICES=0 python eval.py \
    rlbench.tasks=[light_bulb_in] \
    rlbench.task_name='clip_light_bulb_512_p3' \
    rlbench.demo_path=$PERACT_ROOT/data/peract_baseline/test \
    framework.gpu=0 \
    framework.logdir=$PERACT_ROOT/logs/100_demos \
    framework.start_seed=0 \
    framework.eval_envs=1 \
    framework.eval_from_eps_number=0 \
    framework.eval_episodes=25 \
    framework.csv_logging=True \
    framework.tensorboard_logging=False \
    framework.eval_type='best' \
    rlbench.headless=True \
    rlbench.episode_length=12

CUDA_VISIBLE_DEVICES=0 python train.py \
    method=PERACT_BC \
    rlbench.tasks=\[light_bulb_in\] \
    rlbench.task_name='test' \
    rlbench.cameras=\[front,left_shoulder,right_shoulder,wrist\] \
    rlbench.demos=2 \
    rlbench.demo_path=$PERACT_ROOT/data/peract_baseline/train \
    replay.batch_size=4 \
    replay.path=/tmp/replay \
    replay.max_parallel_processes=2 \
    method.voxel_sizes=\[100\] \
    method.voxel_patch_size=5 \
    method.voxel_patch_stride=5 \
    method.num_latents=512 \
    method.transform_augmentation.apply_se3=True \
    method.transform_augmentation.aug_rpy=\[0.0,0.0,45.0\] \
    method.pos_encoding_with_lang=True \
    framework.training_iterations=20100\
    framework.num_weights_to_keep=15 \
    framework.start_seed=0 \
    framework.log_freq=500 \
    framework.save_freq=1000 \
    framework.logdir=$PERACT_ROOT/logs/100_demos/ \
    framework.csv_logging=True \
    framework.tensorboard_logging=True \
    ddp.num_devices=1 \
    rlbench.episode_length=12 \
    method.dense_clip_sims=True \
    method.no_rgb=True

CUDA_VISIBLE_DEVICES=0 python eval.py \
    rlbench.tasks=[close_jar,light_bulb_in] \
    rlbench.task_name='clip_multi_jar_bulb_rls2' \
    rlbench.demo_path=$PERACT_ROOT/data/peract_baseline/test \
    framework.gpu=0 \
    framework.logdir=$PERACT_ROOT/logs/100_demos \
    framework.start_seed=0 \
    framework.eval_envs=4 \
    framework.eval_from_eps_number=0 \
    framework.eval_episodes=25 \
    framework.csv_logging=True \
    framework.tensorboard_logging=False \
    framework.eval_type=27000 \
    rlbench.headless=True \
    rlbench.episode_length=12

CUDA_VISIBLE_DEVICES=0 python train.py \
    method=PERACT_BC \
    rlbench.tasks=\[place_shape_in_shape_sorter\] \
    rlbench.task_name='clip_shape_sorter_1024_p3' \
    rlbench.cameras=\[front,left_shoulder,right_shoulder,wrist\] \
    rlbench.demos=100 \
    rlbench.demo_path=$PERACT_ROOT/data/peract_baseline/train \
    replay.batch_size=3 \
    replay.path=$PERACT_ROOT/replay \
    replay.max_parallel_processes=15 \
    method.voxel_sizes=\[100\] \
    method.voxel_patch_size=5 \
    method.voxel_patch_stride=5 \
    method.num_latents=1024 \
    method.transform_augmentation.apply_se3=True \
    method.transform_augmentation.aug_rpy=\[0.0,0.0,45.0\] \
    method.pos_encoding_with_lang=True \
    framework.training_iterations=20001\
    framework.num_weights_to_keep=21 \
    framework.start_seed=0 \
    framework.log_freq=500 \
    framework.save_freq=500 \
    framework.logdir=$PERACT_ROOT/logs/100_demos/ \
    framework.csv_logging=True \
    framework.tensorboard_logging=True \
    ddp.num_devices=1 \
    rlbench.episode_length=15 \
    method.dense_clip_sims=True \
    method.no_rgb=True

CUDA_VISIBLE_DEVICES=0 python eval.py \
    rlbench.tasks=\[place_shape_in_shape_sorter\] \
    rlbench.task_name='clip_shape_sorter_1024_p3' \
    rlbench.demo_path=$PERACT_ROOT/data/peract_baseline/test \
    framework.gpu=0 \
    framework.logdir=$PERACT_ROOT/logs/100_demos \
    framework.start_seed=0 \
    framework.eval_envs=1 \
    framework.eval_from_eps_number=0 \
    framework.eval_episodes=25 \
    framework.csv_logging=True \
    framework.tensorboard_logging=False \
    framework.eval_type='best' \
    rlbench.headless=True \
    rlbench.episode_length=15

CUDA_VISIBLE_DEVICES=0 python eval.py \
    rlbench.tasks=\[a_spheres\] \
    rlbench.task_name='blocks_clip_rls2' \
    rlbench.demo_path=$PERACT_ROOT/data/test \
    framework.gpu=0 \
    framework.logdir=$PERACT_ROOT/logs/100_demos \
    framework.start_seed=0 \
    framework.eval_envs=1 \
    framework.eval_from_eps_number=0 \
    framework.eval_episodes=5 \
    framework.csv_logging=False \
    framework.tensorboard_logging=False \
    framework.eval_type='best' \
    rlbench.headless=False \
    rlbench.episode_length=15

python dataset_generator.py --tasks=a_stack_blocks \
                            --save_path=$PERACT_ROOT/data \
                            --image_size=128,128 \
                            --renderer=opengl \
                            --episodes_per_task=25 \
                            --processes=1 \
                            --all_variations=True

python dataset_generator.py --tasks=a_spheres \
                            --save_path=$PERACT_ROOT/data \
                            --image_size=128,128 \
                            --renderer=opengl \
                            --episodes_per_task=2 \
                            --processes=1 \
                            --all_variations=True

CUDA_VISIBLE_DEVICES=0 python train.py \
    method=PERACT_BC \
    rlbench.tasks=\[a_stack_blocks\] \
    rlbench.task_name='blocks_clip_rls2' \
    rlbench.cameras=\[front,left_shoulder,right_shoulder,wrist\] \
    rlbench.demos=100 \
    rlbench.demo_path=$PERACT_ROOT/data/train \
    replay.batch_size=3 \
    replay.path=$PERACT_ROOT/replay \
    replay.max_parallel_processes=15 \
    method.voxel_sizes=\[100\] \
    method.voxel_patch_size=5 \
    method.voxel_patch_stride=5 \
    method.num_latents=2048 \
    method.transform_augmentation.apply_se3=True \
    method.transform_augmentation.aug_rpy=\[0.0,0.0,0.0\] \
    method.pos_encoding_with_lang=True \
    framework.training_iterations=15001\
    framework.num_weights_to_keep=21 \
    framework.start_seed=0 \
    framework.log_freq=500 \
    framework.save_freq=500 \
    framework.logdir=$PERACT_ROOT/logs/100_demos/ \
    framework.csv_logging=True \
    framework.tensorboard_logging=True \
    ddp.num_devices=1 \
    method.dense_clip_sims=True \
    method.no_rgb=True \
    rlbench.episode_length=15 
    # framework.load_existing_weights=True